// Real first-level administrative divisions for each BRICS nation
// Used to populate the State/Province dropdown in the report form

export const COUNTRY_LIST = [
  'Brazil',
  'Russia',
  'India',
  'China',
  'South Africa',
  'Egypt',
  'Ethiopia',
  'Iran',
  'Saudi Arabia',
  'UAE',
] as const;

export type CountryName = (typeof COUNTRY_LIST)[number];

export const COUNTRY_STATES: Record<CountryName, string[]> = {
  Brazil: [
    'São Paulo',
    'Rio de Janeiro',
    'Minas Gerais',
    'Bahia',
    'Paraná',
    'Rio Grande do Sul',
    'Pernambuco',
    'Ceará',
    'Pará',
    'Maranhão',
    'Santa Catarina',
    'Goiás',
    'Amazonas',
    'Espírito Santo',
    'Mato Grosso',
  ],
  Russia: [
    'Moscow Oblast',
    'Saint Petersburg',
    'Krasnodar Krai',
    'Sverdlovsk Oblast',
    'Novosibirsk Oblast',
    'Tatarstan',
    'Nizhny Novgorod Oblast',
    'Samara Oblast',
    'Rostov Oblast',
    'Chelyabinsk Oblast',
    'Voronezh Oblast',
    'Kemerovo Oblast',
  ],
  India: [
    'Maharashtra',
    'Karnataka',
    'Tamil Nadu',
    'Kerala',
    'Delhi',
    'Uttar Pradesh',
    'West Bengal',
    'Gujarat',
    'Rajasthan',
    'Bihar',
    'Telangana',
    'Andhra Pradesh',
    'Madhya Pradesh',
    'Punjab',
    'Haryana',
    'Odisha',
    'Assam',
    'Jharkhand',
  ],
  China: [
    'Guangdong',
    'Jiangsu',
    'Shandong',
    'Zhejiang',
    'Henan',
    'Sichuan',
    'Hubei',
    'Hunan',
    'Hebei',
    'Fujian',
    'Beijing',
    'Shanghai',
    'Tianjin',
    'Chongqing',
    'Anhui',
    'Jiangxi',
    'Shaanxi',
    'Liaoning',
  ],
  'South Africa': [
    'Gauteng',
    'Western Cape',
    'KwaZulu-Natal',
    'Eastern Cape',
    'Free State',
    'Mpumalanga',
    'Limpopo',
    'North West',
    'Northern Cape',
  ],
  Egypt: [
    'Cairo Governorate',
    'Giza Governorate',
    'Alexandria Governorate',
    'Dakahlia Governorate',
    'Sharqia Governorate',
    'Qalyubia Governorate',
    'Beheira Governorate',
    'Gharbia Governorate',
    'Monufia Governorate',
    'Asyut Governorate',
    'Suez Governorate',
  ],
  Ethiopia: [
    'Addis Ababa',
    'Oromia',
    'Amhara',
    'Tigray',
    'Sidama',
    'Somali Region',
    'Southern Nations, Nationalities, and Peoples',
    'Afar',
    'Benishangul-Gumuz',
    'Gambela',
    'Hariari',
  ],
  Iran: [
    'Tehran Province',
    'Isfahan Province',
    'Fars Province',
    'Khorasan Razavi',
    'Mazandaran Province',
    'Khuzestan Province',
    'East Azerbaijan',
    'West Azerbaijan',
    'Gilam Province',
    'Kerman Province',
    'Alborz Province',
  ],
  'Saudi Arabia': [
    'Riyadh Province',
    'Makkah Province',
    'Eastern Province',
    'Asir Province',
    'Madinah Province',
    'Tabuk Province',
    'Qassim Province',
    'Hail Province',
    'Northern Borders Province',
    'Jazan Province',
  ],
  UAE: [
    'Abu Dhabi',
    'Dubai',
    'Sharjah',
    'Ajman',
    'Ras Al Khaimah',
    'Fujairah',
    'Umm Al Quwain',
  ],
};
