import type { Complaint, Cluster } from './types';

// Mock data matching the Firestore schema — used as fallback when Firestore is
// unreachable or returns empty, so every screen always has something to show.

const now = Date.now();
const DAY = 86400000;

export const mockComplaints: Complaint[] = [
  {
    id: 'mock-c001',
    category: 'Water',
    location: 'Koramangala, Karnataka, India',
    issue_summary: 'No water supply for 3 days in our ward. The pipeline seems broken near 5th block.',
    transcript: null,
    language: 'en',
    pseudonymous_id: 'anon-001',
    verification_status: 'needs_review',
    priority_score: 0,
    cluster_id: 'mock-cl01',
    created_at: now - 2 * DAY,
  },
  {
    id: 'mock-c002',
    category: 'Water',
    location: 'Indiranagar, Karnataka, India',
    issue_summary: 'Water pressure very low for the past week. Hard to get any water in mornings.',
    transcript: null,
    language: 'en',
    pseudonymous_id: 'anon-002',
    verification_status: 'needs_review',
    priority_score: 0,
    cluster_id: 'mock-cl01',
    created_at: now - 1.5 * DAY,
  },
  {
    id: 'mock-c003',
    category: 'Roads',
    location: 'Jubilee Hills, Telangana, India',
    issue_summary: 'Large potholes on Road No. 36 causing accidents every day.',
    transcript: null,
    language: 'hi',
    pseudonymous_id: 'anon-003',
    verification_status: 'verified',
    priority_score: 78,
    cluster_id: 'mock-cl02',
    created_at: now - 5 * DAY,
  },
  {
    id: 'mock-c004',
    category: 'Roads',
    location: 'Banjara Hills, Telangana, India',
    issue_summary: 'Road surface completely broken after recent rains near KBR Park entrance.',
    transcript: null,
    language: 'en',
    pseudonymous_id: 'anon-004',
    verification_status: 'verified',
    priority_score: 78,
    cluster_id: 'mock-cl02',
    created_at: now - 4 * DAY,
  },
  {
    id: 'mock-c005',
    category: 'Electricity',
    location: 'Copacabana, Rio de Janeiro, Brazil',
    issue_summary: 'Frequent power outages every evening for the past two weeks.',
    transcript: null,
    language: 'pt',
    pseudonymous_id: 'anon-005',
    verification_status: 'needs_review',
    priority_score: 0,
    cluster_id: 'mock-cl03',
    created_at: now - 3 * DAY,
  },
  {
    id: 'mock-c006',
    category: 'Sanitation',
    location: 'Soweto, Gauteng, South Africa',
    issue_summary: 'Sewage overflow in the streets near the community center.',
    transcript: null,
    language: 'zu',
    pseudonymous_id: 'anon-006',
    verification_status: 'invalid',
    priority_score: 15,
    cluster_id: 'mock-cl04',
    created_at: now - 7 * DAY,
  },
  {
    id: 'mock-c007',
    category: 'Water',
    location: 'HSR Layout, Karnataka, India',
    issue_summary: 'Contaminated water coming from the tap, smells bad.',
    transcript: null,
    language: 'en',
    pseudonymous_id: 'anon-007',
    verification_status: 'needs_review',
    priority_score: 0,
    cluster_id: 'mock-cl01',
    created_at: now - 0.5 * DAY,
  },
  {
    id: 'mock-c008',
    category: 'Electricity',
    location: 'Ipanema, Rio de Janeiro, Brazil',
    issue_summary: 'Street lights not working on the main avenue for a month.',
    transcript: null,
    language: 'pt',
    pseudonymous_id: 'anon-008',
    verification_status: 'needs_review',
    priority_score: 0,
    cluster_id: 'mock-cl03',
    created_at: now - 2.5 * DAY,
  },
];

export const mockClusters: Cluster[] = [
  {
    id: 'mock-cl01',
    category: 'Water',
    location_bucket: 'Karnataka, India',
    count: 3,
    verification_status: 'needs_review',
    priority_score: 0,
    country: 'India',
  },
  {
    id: 'mock-cl02',
    category: 'Roads',
    location_bucket: 'Telangana, India',
    count: 2,
    verification_status: 'verified',
    priority_score: 78,
    country: 'India',
  },
  {
    id: 'mock-cl03',
    category: 'Electricity',
    location_bucket: 'Rio de Janeiro, Brazil',
    count: 2,
    verification_status: 'needs_review',
    priority_score: 0,
    country: 'Brazil',
  },
  {
    id: 'mock-cl04',
    category: 'Sanitation',
    location_bucket: 'Gauteng, South Africa',
    count: 1,
    verification_status: 'invalid',
    priority_score: 15,
    country: 'South Africa',
  },
];
